const studentdata=[
    {
        id:"1",
        name:"palak",
        email:"palak@gmail.com",
        phone:"13213"
    },
    {
        id:"2",
        name:"priya",
        email:"riya@gmail.com",
        phone:"7889"
    },
    {
        id:"3",
        name:"richa",
        email:"richa@gmail.com",
        phone:"7889"
    },
]